<footer>
	<ul>
		<li><a href="index.php?page=home"> Accueil </a></li>
		<li><a href="index.php?page=home"> Nous contacter </a></li>
	</ul>

	<br>

	<div class="menu_res_sociaux">
		<div class="menu_res">
			<ul class="res_sociaux">
				<li><a href="#" id="facebook" class="sprite ico-facebook"></a></li>
				<li><a href="#" id="twitter" class="sprite ico-twitter"></a></li>
			</ul>
		</div>
	</div>
	<p> Un projet 3WA - K2G (Kris - Gael - Geoffrey) </p>
</footer>