<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>Chat</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<link rel="stylesheet" type="text/css" href="public/styles/reset.css" />
	<link rel="stylesheet" href="public/styles/style.css">
	<script src="public/scripts/jquery.js"></script>
	<script src="public/scripts/script.js"></script>
</head>
<body>
	<header class="header">
		<?php require('apps/header.php'); ?>
	</header>
	<main class="main">
		<?php require('apps/content.php'); ?>
	</main>
	<footer class="footer">
		<?php require('apps/footer.php'); ?>
	</footer>
</body>
</html>